index:
    path: /
    controller: App\Controller\FrontController::index

home:
    path: /home
    controller: App\Controller\FrontController::home


yelloLily.maria:
    path: /yellowLily/maria
    controller: App\Controller\FrontController::maria

yelloLily.seniors:
    path: /yellowLily/seniors
    controller: App\Controller\FrontController::seniors
